In [1]:
import pandas as pd


df = pd.read_parquet('../data/yellow_tripdata_2026-01.parquet',engine='fastparquet')

In [3]:
print(f'{len(df):,}')

3,724,889

In [4]:
df.head(5)

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
0,2,2026-01-01 00:54:04,2026-01-01 00:59:37,1.0,0.97,1.0,N,239,238,1,7.2,1.00,0.5,3.66,0.0,1.0,15.86,2.5,0.0,0.00
1,1,2026-01-01 00:34:04,2026-01-01 00:39:47,0.0,0.90,1.0,N,163,162,2,7.9,4.25,0.5,0.00,0.0,1.0,13.65,2.5,0.0,0.75
2,1,2026-01-01 00:57:06,2026-01-01 01:05:59,0.0,1.40,1.0,N,43,237,1,10.7,4.25,0.5,2.50,0.0,1.0,18.95,2.5,0.0,0.75
3,2,2026-01-01 00:15:22,2026-01-01 00:58:10,4.0,5.58,1.0,N,142,209,1,38.7,1.00,0.5,11.11,0.0,1.0,55.56,2.5,0.0,0.75
4,2,2026-01-01 00:27:13,2026-01-01 00:40:43,0.0,2.16,1.0,N,88,144,1,13.5,1.00,0.5,3.85,0.0,1.0,23.10,2.5,0.0,0.75

In [5]:
summary = df.describe().T.assign(
    distinct_count = df.nunique(),
    missing_counts = df.isna().sum() , 
    missing_precetage = (df.isna().mean()*100).round(2)
)[['count','distinct_count','missing_counts' , 'missing_precetage' , 'min', 'max']]

In [6]:
summary

,count,distinct_count,missing_counts,missing_precetage,min,max
VendorID,3724889.0,4,0,0.00,1.0,7.0
tpep_pickup_datetime,3724889,1757191,0,0.00,2025-12-31 23:57:29,2026-02-01 00:45:01
tpep_dropoff_datetime,3724889,1755995,0,0.00,2025-12-31 23:57:32,2026-02-01 23:35:31
passenger_count,2636831.0,10,1088058,29.21,0.0,9.0
trip_distance,3724889.0,4777,0,0.00,0.0,269097.48
RatecodeID,2636831.0,7,1088058,29.21,1.0,99.0
PULocationID,3724889.0,262,0,0.00,1.0,265.0
DOLocationID,3724889.0,260,0,0.00,1.0,265.0
payment_type,3724889.0,5,0,0.00,0.0,4.0
fare_amount,3724889.0,12867,0,0.00,-2555.2,2555.2
extra,3724889.0,45,0,0.00,-7.5,17.46
mta_tax,3724889.0,6,0,0.00,-0.5,4.75
tip_amount,3724889.0,4326,0,0.00,-88.88,766.0
tolls_amount,3724889.0,1495,0,0.00,-94.5,122.22
improvement_surcharge,3724889.0,4,0,0.00,-1.0,1.0
total_amount,3724889.0,21228,0,0.00,-2560.2,2560.2
congestion_surcharge,2636831.0,3,1088058,29.21,-2.5,2.5
Airport_fee,2636831.0,8,1088058,29.21,-1.75,26.75
cbd_congestion_fee,3724889.0,3,0,0.00,-0.75,0.75

In [7]:
## Business Rules


pass_count = len(df[ df['passenger_count']==0])
print(pass_count)

bad_dates_count = len(df[ df['tpep_pickup_datetime'] >= df['tpep_dropoff_datetime']])
print(bad_dates_count)

distance_less_th_zero = len(df[ df['trip_distance']<= 0 ])
print(distance_less_th_zero)


total_amount =len(df[ df['total_amount']<= 0 ])
print(total_amount)

14787
45070
125738
40417

In [8]:
df[ df['tpep_pickup_datetime'] > df['tpep_dropoff_datetime']].head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
1465434,1,2026-01-17 19:30:00,2026-01-17 19:18:18,1.0,16.5,99.0,N,46,86,1,66.5,0.0,0.5,0.0,0.0,0.0,67.0,0.0,0.0,0.0

In [9]:
df[  (df['RatecodeID'].isnull())]

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
2636831,2,2026-01-01 00:28:47,2026-01-01 00:49:30,NaN,10.58,NaN,None,43,200,0,82.01,0.0,0.5,0.0,3.18,1.0,89.19,NaN,NaN,0.00
2636832,2,2026-01-01 00:54:24,2026-01-01 01:15:01,NaN,11.04,NaN,None,200,51,0,51.77,0.0,0.5,0.0,0.00,1.0,53.27,NaN,NaN,0.00
2636833,2,2026-01-01 00:12:31,2026-01-01 00:41:02,NaN,4.25,NaN,None,142,234,0,32.17,0.0,0.5,0.0,0.00,1.0,36.92,NaN,NaN,0.75
2636834,2,2026-01-01 00:48:56,2026-01-01 01:08:00,NaN,2.05,NaN,None,90,114,0,18.29,0.0,0.5,1.0,0.00,1.0,24.04,NaN,NaN,0.75
2636835,2,2026-01-01 00:32:09,2026-01-01 00:41:05,NaN,0.97,NaN,None,237,163,0,15.02,0.0,0.5,0.0,0.00,1.0,22.77,NaN,NaN,0.75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3724884,2,2026-01-31 23:26:00,2026-01-31 23:39:16,NaN,1.62,NaN,None,237,161,0,17.09,0.0,0.5,0.0,0.00,1.0,21.84,NaN,NaN,0.75
3724885,2,2026-01-31 23:33:53,2026-01-31 23:34:07,NaN,0.00,NaN,None,42,42,0,23.19,0.0,0.5,0.0,0.00,1.0,24.69,NaN,NaN,0.00
3724886,2,2026-01-31 23:40:23,2026-01-31 23:56:10,NaN,6.84,NaN,None,137,69,0,29.21,0.0,0.5,0.0,0.00,1.0,33.96,NaN,NaN,0.75
3724887,2,2026-01-31 23:10:21,2026-01-31 23:20:00,NaN,1.53,NaN,None,137,162,0,19.19,0.0,0.5,0.0,0.00,1.0,23.94,NaN,NaN,0.75
3724888,2,2026-01-31 23:43:12,2026-01-31 23:57:45,NaN,1.04,NaN,None,148,148,0,16.49,0.0,0.5,0.0,0.00,1.0,21.24,NaN,NaN,0.75

In [10]:
print(df['RatecodeID'].value_counts())
print(df['payment_type'].value_counts())
print(df['PULocationID'].value_counts())
print(df['DOLocationID'].value_counts())

RatecodeID
1.0     2390495
99.0     110864
2.0       83592
5.0       32030
3.0       11541
4.0        8304
6.0           5
Name: count, dtype: int64
payment_type
1    2249747
0    1088058
2     314043
4      56400
3      16641
Name: count, dtype: int64
PULocationID
237    160343
236    153640
132    152589
161    146641
186    110700
        ...
199         3
105         2
204         2
99          1
44          1
Name: count, Length: 262, dtype: int64
DOLocationID
236    156661
237    146726
161    121571
170     99583
230     99157
        ...
44         25
204        16
5          14
2          12
99          2
Name: count, Length: 260, dtype: int64

In [44]:
precentags = [ 0.25 , 0.50 , 0.75 , 0.95 , 0.99 ,0.999] 
print(df['trip_distance'].describe(percentiles=precentags).round(2)[['min' ,'max', '25%' , '50%', '75%','95%','99%','99.9%']])
print(df['fare_amount'].describe(percentiles=precentags).round(2)[['min' ,'max', '25%' , '50%', '75%','95%','99%','99.9%']])
print(df['total_amount'].describe(percentiles=precentags).round(2)[['min' ,'max', '25%' , '50%', '75%','95%','99%','99.9%']])

min           0.00
max      269097.48
25%           1.00
50%           1.81
75%           3.73
95%          12.45
99%          19.54
99.9%        29.79
Name: trip_distance, dtype: float64
min     -2555.2
max      2555.2
25%        10.0
50%        15.6
75%        26.1
95%        58.5
99%        81.4
99.9%     145.8
Name: fare_amount, dtype: float64
min     -2560.20
max      2560.20
25%        17.00
50%        23.05
75%        33.83
95%        75.25
99%       104.75
99.9%     175.51
Name: total_amount, dtype: float64

In [ ]:
print(df[ (df['trip_distance'] > 145.8)])
print(df[  df['total_amount'] < 0]['payment_type'].value_counts())
print(df[  df['total_amount'] < 0]['store_and_fwd_flag'].value_counts())
print(df[  df['total_amount'] < 0]['VendorID'].value_counts())

payment_type
4    26039
2     9170
3     4493
1      268
0       14
Name: count, dtype: int64
store_and_fwd_flag
N    39970
Name: count, dtype: int64
VendorID
2    39984
Name: count, dtype: int64

In [73]:
len(df[  (df['passenger_count'] <= 0) |  (df['passenger_count'].isnull()) ])

1102845

In [41]:



df.duplicated().sum()

np.int64(0)

In [42]:
df[df['passenger_count'].isnull()]['VendorID'].value_counts()

VendorID
2    944635
1    139406
6      4017
Name: count, dtype: int64

In [43]:
df[df['passenger_count'].isnull()]['tpep_pickup_datetime'].dt.date.value_counts()

tpep_pickup_datetime
2026-01-30    56589
2026-01-31    55680
2026-01-24    53977
2026-01-01    47482
2026-01-10    46641
2026-01-29    46640
2026-01-18    44607
2026-01-17    42414
2026-01-28    42255
2026-01-27    42229
2026-01-23    39765
2026-01-16    36617
2026-01-11    35167
2026-01-15    33827
2026-01-20    33469
2026-01-22    32798
2026-01-21    31771
2026-01-19    29313
2026-01-14    29106
2026-01-09    29070
2026-01-03    28865
2026-01-26    28200
2026-01-13    27970
2026-01-04    26433
2026-01-25    26097
2026-01-12    25490
2026-01-08    25084
2026-01-02    24273
2026-01-07    23798
2026-01-06    22078
2026-01-05    20353
Name: count, dtype: int64

In [81]:
df[ (df['trip_distance'] > 145.8)].sort_values(by=['trip_distance'] , ascending=False)[['payment_type' , 'VendorID','RatecodeID' ]].value_counts()

payment_type  VendorID  RatecodeID
1             1         99.0          4
              2         5.0           2
                        1.0           2
2             2         4.0           1
1             2         4.0           1
              1         5.0           1
Name: count, dtype: int64

In [ ]:
print(len(df[ df['passenger_count'] == 0]))
# 14787

print(len(df[ df['passenger_count'].isnull()]))
#1088058

14787
1088058

In [62]:
1088058 + 14787

1102845

In [72]:
temp = pd.DataFrame({
    'name':['Kola' , None]
})


len(temp[temp['name'].isna()])

1

In [76]:
total_by_vendor = df['VendorID'].value_counts()
null_by_vendor = df[df['passenger_count'].isnull()]['VendorID'].value_counts()
null_rate_by_vendor = (null_by_vendor / total_by_vendor * 100).round(2)

In [77]:
print(total_by_vendor )
print(null_by_vendor)
print(null_rate_by_vendor )

VendorID
2    2965742
1     710425
7      44705
6       4017
Name: count, dtype: int64
VendorID
2    944635
1    139406
6      4017
Name: count, dtype: int64
VendorID
1     19.62
2     31.85
6    100.00
7       NaN
Name: count, dtype: float64

In [79]:
df['payment_type'].value_counts()

payment_type
1    2249747
0    1088058
2     314043
4      56400
3      16641
Name: count, dtype: int64

In [ ]:
import datetime

# Now your line will run perfectly
filtered_df = df[df['tpep_pickup_datetime'].dt.date < datetime.date(2026, 1, 1)]
print(len(filtered_df))
filtered_df = df[df['tpep_pickup_datetime'].dt.date > datetime.date(2026, 1, 31)]
print(len(filtered_df))


# Now your line will run perfectly
filtered_df = df[df['tpep_pickup_datetime'].dt.date < datetime.date(2026, 1, 1)]
print(len(filtered_df))
filtered_df = df[df['tpep_pickup_datetime'].dt.date > datetime.date(2026, 1, 31)]
print(len(filtered_df))

6
1

In [94]:
df.head(5)

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
0,2,2026-01-01 00:54:04,2026-01-01 00:59:37,1.0,0.97,1.0,N,239,238,1,7.2,1.00,0.5,3.66,0.0,1.0,15.86,2.5,0.0,0.00
1,1,2026-01-01 00:34:04,2026-01-01 00:39:47,0.0,0.90,1.0,N,163,162,2,7.9,4.25,0.5,0.00,0.0,1.0,13.65,2.5,0.0,0.75
2,1,2026-01-01 00:57:06,2026-01-01 01:05:59,0.0,1.40,1.0,N,43,237,1,10.7,4.25,0.5,2.50,0.0,1.0,18.95,2.5,0.0,0.75
3,2,2026-01-01 00:15:22,2026-01-01 00:58:10,4.0,5.58,1.0,N,142,209,1,38.7,1.00,0.5,11.11,0.0,1.0,55.56,2.5,0.0,0.75
4,2,2026-01-01 00:27:13,2026-01-01 00:40:43,0.0,2.16,1.0,N,88,144,1,13.5,1.00,0.5,3.85,0.0,1.0,23.10,2.5,0.0,0.75

In [2]:
from data_profiling import ProfileReport

profile = ProfileReport(df, title="Profiling Report" , minimal=True)
profile.to_file('Yellow_report.html')

/home/linux/Desktop/data-engineering-projects/NYC-Taxi/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
100%|██████████| 20/20 [00:26<00:00,  1.31s/it]6<00:02,  1.67it/s, Describe variable: cbd_congestion_fee]
Summarize dataset: 100%|██████████| 26/26 [00:26<00:00,  1.01s/it, Completed]
Generate report structure: 100%|██████████| 1/1 [00:04<00:00,  4.53s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  3.44it/s]
Export report to file: 100%|██████████| 1/1 [00:00<00:00, 132.20it/s]